### ISSUE TITLE
Rounded Corners Effect not working

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/image_effects#11]
I was just doing a Backdrop demo and tried the "Rounded Corners" effect, but it doesn't seem to work. My final images are not getting this effect. 

I tried other effects that did work. 

Sorry, I don't have time to debug this further right now, but wanted to share that this might be a problem.

**Comment by laryn** [comment]
Thanks @stpaultim. I'll be honest, I've never used that effect -- usually do rounded corners in CSS these days. If you get a chance to post any error messages here, I'm guessing it's a simple fix.
