### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/image_effects#18]
I noticed that PHP image functions have changed with PHP 8. It would be good to test some of these functions to make sure that they still work on PHP 8. 

> image expects a [GdImage](https://www.php.net/manual/en/class.gdimage.php) instance now; previously, a resource was expected.

**Comment by laryn** [comment]
I spun up a Lando site with PHP 8.0 and tested the dev branch from https://github.com/backdrop-contrib/image_effects/issues/16 which seems to work fine so I'll close this for now.

**Comment by indigoxela** [comment]
FTR, I just checked the PR from #16 on php 8.1 - still works, no problem. :+1:
