### ISSUE TITLE
Cannot install using the installer UI

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/image_effects#7]
When trying to install using the install UI at /admin/modules/install I get this error:

> Error installing Image Effects. Unable to retrieve Backdrop project from https://github.com/backdrop-contrib/image_effects/releases/download/1.x-1.9.0-beta/image_effects.zip.

Maybe it doesn't like the `-beta` on the end? I'm not sure. @laryn

**Comment by laryn** [comment]
@herbdool I just tested and didn't have a problem. Can you install other modules on the site in question?

**Comment by laryn** [comment]
@herbdool I just made a new release. Are you still seeing this issue?

**Comment by herbdool** [comment]
I was able to install it via the UI. Looks good!
